runtime: python
env: flex
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app

runtime_config:
  python_version: 3.7

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6